### ISSUE TITLE
Week 1: update discussion section

### ISSUE THREAD

**Issue by ryoliver** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#5]
Updates needed:

- [x] rewrite instructions in the style of end of day activities from summer session (example [here](https://eds-221-programming-essentials.github.io/course-materials/eod-practice/eod-day1.html))
- [x] find environmental data to work with
- [x] create answer key

@avidalmeza @julietcohen

**Comment by julietcohen** [comment]
Recreating a figure sounds like a fun assignment! Especially if they are required or encouraged to add another vector or raster layer to test their creativity. We could look for some example vector datasets that overlap with the same region and include them in the data dir for them to overlay in addition to the volcanos layer, or provide alternative raster layers that they could swap out for the elevation raster and have to choose a new palette and description for what the map now represents, like "the resolution is appropriate" or "the CRS has been transformed to match" or "now we can use these layer in conjunction to understand this new thing."

Of course I don't want to assume that MEDS students are looking for the answers online rather than trying to write the code themselves, because I am sure they're motivated to do so, but I wonder if it would be _too_ easy to find that original `tmap` code since that book resource is open source.

**Comment by julietcohen** [comment]
As an example of additonal/alternative datasets to provide, we can download bathymetry raster data (and other datasets) from NOAA using their portal and a drawn bbox. [Here](https://noaa.maps.arcgis.com/home/item.html?id=0441041574c544dc9b6b8a513cad5e95) is the dataset description.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/3038ce24-ad85-4d19-b8c1-15fdc64d5046">

**Comment by julietcohen** [comment]
Along the same thinking, Cullen suggested we could use the NOAA API `marmap` to load in bathymetry data that seems like it is interpolated closer to the island edges. [Here](https://cullen-molitor.github.io/posts/2021-11-29-cartography-in-r/) is his blog post where he shows how he mapped this data with `ggplot`

**Comment by avidalmeza** [comment]
I agree that recreating (and improving) a figure is a good discussion session idea. I like Cullen's suggestion; although we'd probably want to provide the code for how we got the data and not make them work directly with an API during week 1.

**Comment by avidalmeza** [comment]
I lean towards thinking that including textbook examples is okay for a discussion session, but maybe students would prefer non-textbook examples since they are expected to review the textbook on their own time?

**Comment by julietcohen** [comment]
Adding the bathymetry raster layer from the NOAA portal is simple but I'm not loving the patchiness:
![image](https://github.com/user-attachments/assets/f9f74880-5d43-4e9e-9bcb-46f9607ef3a0)


I agree that it may be challenging for the students to use the API. If you do want to move forward with Easter Island and `marmap` bathymetry in general we could use the API and upload the data to the dir for them, or download it manually like I did from the portal.

**Comment by ryoliver** [comment]
I really like the idea to add new data to it! Discussion sections are pretty short (50 minutes), so I think we should keep it to just reproducing the figure, but I think this would be a great addition to Homework Assignment 1. Basically, they would reproduce the figure in discussion section and then in their homework they would need to add new data (including checking CRSs). It could be a nice conceptual bridge between the guided exercises in discussion section and working independently on their homework. (HW1 also asks them to make a map from the EJScreen data by selecting a region and information they're interested in)

**Comment by avidalmeza** [comment]
@julietcohen and I were chatting about the bathymetry raster data for Homework Assignment 1. Should we provide them a raster before we cover rasters in class? The counterargument is that they will have the code and won't otherwise learn about map making with rasters. I could alternatively cover this same example in week 6 or 7 during discussion section. What do you both think?

**Comment by ryoliver** [comment]
I think it's ok to include raster data in HW 1. I will give a brief intro in class and they will see a couple of examples in class. As long as we give them the code for reading in the data they should ok (famous last words!)
